# config.py - Property Inspection API Keys
# KEEP THIS FILE PRIVATE - do not upload to public GitHub

IMAGGA_API_KEY = "YOUR_IMAGGA_API_KEY_HERE"
IMAGGA_API_SECRET = "YOUR_IMAGGA_API_SECRET_KEY_HERE"
OCRSPACE_API_KEY = "YOUR_OCRSPACE_API_KEY_HERE"
LOCATIONIQ_API_KEY = "YOUR_LOCATION_API_KEY_HERE"
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"